paper.html:paper.md 00-abstract.md 01-introduction.md 02-discussion.md 03-conclusions.md
	pandoc -s sections/00-abstract.md sections/01-introduction.md sections/02-discussion.md 03-conclusions.md -o paper.md
	pandoc paper.md -o paper.html
	
